### PR TITLE
fix default values that contains a new line

### LINKED ISSUE #8: Export/Import survey multiple choice issue
## Summary

I've discovered that when a survey with multiple-choice questions is exported with JT/WF and then imported, the multiple-choice gets broken - it has only one choice.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

```console (paste below)
ansible --version

ansible [core 2.15.8]

ansible-galaxy collection list
Collection                     Version
------------------------------ -------
ansible.controller                        4.5.10
infra.controller_configuration 2.9.0

```

- ansible installation method: EE

## OS / ENVIRONMENT

RH 9.4

## Desired Behavior

Survey has a list of choices:
```
A
B
C
D
```
## Actual Behavior

Survey has a one choice:
```
A/nB/nC/nD
```

## STEPS TO REPRODUCE
Remark: the object with survey must be migrated from ATP to AAP using upgrade method.
1. Create JT with survey on ATP with multiple choice question, add at least two answers.
2. Upgrade ATP to AAP
3. Export the JT
4. Import the JT

### PR DESCRIPTION
**Pull request by ivarmu**
# What does this PR do?

Fixes #8 
# How should this be tested?

Manually tested.
# Is there a relevant Issue open for this?

resolves #8

# Other Relevant info, PRs, etc

N/A

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by przemkalit** [comment]
Hey, I appreciate the change for my issue, I would like use this PR as opportunity to fix one thing if it is possible, there is small issue related to extra_data of survey in WF. 
```yaml
{{ node.extra_data | to_nice_yaml | indent(10) | replace("'{{", "!unsafe \'{{") | replace("$encrypted$", "")
```

In result the `encrypted` is changed into nothing - which break the import, so I proposing this change.

```yaml
{{ node.extra_data | to_nice_yaml | indent(10) | replace("'{{", "!unsafe \'{{") | replace("$encrypted$", "''") | replace("'", '"') }}
```

As the survey will use `"`, I am replacing `'` into `"`, as in survey.

**Comment by djdanielsson** [comment]
I also think if you rebase it should fix the CI

**Comment by ivarmu** [comment]
> Hey, I appreciate the change for my issue, I would like use this PR as opportunity to fix one thing if it is possible, there is small issue related to extra_data of survey in WF.
> 
> ```yaml
> {{ node.extra_data | to_nice_yaml | indent(10) | replace("'{{", "!unsafe \'{{") | replace("$encrypted$", "")
> ```
> 
> In result the `encrypted` is changed into nothing - which break the import, so I proposing this change.
> 
> ```yaml
> {{ node.extra_data | to_nice_yaml | indent(10) | replace("'{{", "!unsafe \'{{") | replace("$encrypted$", "''") | replace("'", '"') }}
> ```
> 
> As the survey will use `"`, I am replacing `'` into `"`, as in survey.

I've replaced the `""` with `"\'\'"` everywhere `$encrypted` was replaced.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Pull request merged**
